# Generated by Django 5.1.2 on 2024-10-25 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='rbi.empresa')),
            ],
            options={
                'db_table': 'rbi_area',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroproposta', models.CharField(blank=True, max_length=8, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_componente', to='rbi.componente')),
            ],
        ),
        migrations.CreateModel(
            name='Abavolumemassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumeequip', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumecomponente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numeroproposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_componente5', to='rbi.proposta')),
            ],
        ),
        migrations.CreateModel(
            name='Abaequipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoequipamento', models.CharField(blank=True, max_length=20, null=True)),
                ('nomequipamento', models.CharField(blank=True, max_length=20, null=True)),
                ('descricaoprocesso', models.CharField(blank=True, max_length=20, null=True)),
                ('numeroproposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_componente1', to='rbi.proposta')),
            ],
        ),
        migrations.CreateModel(
            name='Abadadosgerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataavalicao', models.DateField(auto_now_add=True)),
                ('metodoavaliacao', models.CharField(blank=True, max_length=20, null=True)),
                ('periodoavaliado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipogeometriaapi', models.CharField(blank=True, max_length=20, null=True)),
                ('codigoprojeto', models.CharField(blank=True, max_length=20, null=True)),
                ('datainiciooperacao', models.DateField(auto_now_add=True)),
                ('nomecomponente', models.CharField(blank=True, max_length=20, null=True)),
                ('materialcomponente', models.CharField(blank=True, max_length=20, null=True)),
                ('tensaoresistencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tensaoescoamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tensaoadmissivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percenxofre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tratamentotermico', models.BooleanField()),
                ('controleadministrativo', models.BooleanField()),
                ('confiabilidadedados', models.CharField(blank=True, max_length=20, null=True)),
                ('fms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipodeconstrucao', models.CharField(blank=True, max_length=20, null=True)),
                ('manutençãoapi653', models.CharField(blank=True, max_length=20, null=True)),
                ('avaliacaorequalque', models.CharField(blank=True, max_length=20, null=True)),
                ('numeroproposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_componente4', to='rbi.proposta')),
            ],
        ),
        migrations.CreateModel(
            name='Abacondicoesoperacionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressãoprojeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperaturaprojeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperaturamaxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tracoaquecimento', models.BooleanField()),
                ('vazamentovapor', models.BooleanField()),
                ('monitoramento', models.CharField(blank=True, max_length=20, null=True)),
                ('injecao', models.CharField(blank=True, max_length=20, null=True)),
                ('deadleg', models.CharField(blank=True, max_length=20, null=True)),
                ('tipoinspecaodeadleg', models.CharField(blank=True, max_length=20, null=True)),
                ('numeroproposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_componente3', to='rbi.proposta')),
            ],
        ),
        migrations.CreateModel(
            name='Abacomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipocomponenteapi', models.CharField(blank=True, max_length=20, null=True)),
                ('eficienciajunta', models.CharField(blank=True, max_length=20, null=True)),
                ('diametrocomponente', models.CharField(blank=True, max_length=20, null=True)),
                ('raiodacurva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razaomaiormenoreixos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raiocentraltorisferico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raiomenortorisferico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('angulocone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('componentesoldado', models.BooleanField()),
                ('numeroproposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_componente2', to='rbi.proposta')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_tag', to='rbi.areamodel')),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_tag1', to='rbi.tag'),
        ),
    ]
