# Generated by Django 4.2.16 on 2024-10-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0065_alter_tag_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abavolumemassa',
            name='volumeequip',
        ),
        migrations.AddField(
            model_name='abaequipamento',
            name='volumeequip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
