# Generated by Django 4.2.16 on 2024-10-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0066_remove_abavolumemassa_volumeequip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abaequipamento',
            name='data_comissionamento',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterModelTable(
            name='area',
            table='rbi_area',
        ),
    ]
