# Generated by Django 4.2.16 on 2024-10-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0067_abaequipamento_data_comissionamento_alter_area_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='abaequipamento',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
