# Generated by Django 4.2.16 on 2024-10-29 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0068_abaequipamento_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='abaequipamento',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='rbi.tag'),
        ),
    ]
